name: github_authenticator
description: A server that can get OAuth tokens from GitHub.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  http: ^1.0.0
  lints: ^5.0.0
  test: ^1.15.0
